version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      - run:
          name: Install npm wee
          command: yarn
      - run:
          name: Test contracts
          command: npx hardhat test
      - run:
          name: Test coverage
          command: npx hardhat clean && npx hardhat coverage
      - store_artifacts:
          path: reports/coverage
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - node_modules