version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run-test:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          name: Test contracts
          command: npx hardhat test
  run-coverage:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          name: Test coverage
          command: npx hardhat clean && npx hardhat coverage
      - store_artifacts:
          path: reports/coverage
workflows:
  test:
    jobs:
      - run-test
  coverage:
    jobs:
      - run-coverage
