version: 2.1
orbs:
  node: circleci/node@5.0.2
command:
  code-analysis:
    steps:
      - run:
          name: "Sonarqube scanner"
          command: |
            sonar-scanner \
              -Dsonar.projectKey=dTravel_$CIRCLE_PROJECT_REPONAME\
              -Dsonar.sources=. \
              -Dsonar.host.url=$HOST_URL \
              -Dsonar.login=$SONAR_LOGIN \
              -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
              -Dsonar.coverage.exclusions='src/main.ts,src/common/**/*.*,test/*.*,src/**/*.spec.ts'
jobs:
  run-test:
    executor:
      name: node/default
      tag: '16.15.1'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: true
      - run:
          name: Test contracts
          command: npx hardhat test
  run-coverage:
    executor:
      name: node/default
      tag: '16.15.1'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: true
      - run:
          name: Test coverage
          command: npx hardhat clean && npx hardhat coverage
      - store_artifacts:
          path: reports/coverage
      - code-analysis
workflows:
  test:
    jobs:
      - run-test
  coverage:
    jobs:
      - run-coverage
