version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
            - deps-
      # - run:
      #     name: Update npm
      #     command: 'npm i'
      
      # - run:
      #     name: Install npm wee
      #     command: npm install
      - run:
          name: Test Contracts
          command: npx hardhat test
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - node_modules